version: '3.8'

services:
  laptop-advisor:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    command: python app.py
    restart: unless-stopped